version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - '3002:3000'
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    env_file:
      - .env.local
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:4000
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - '4000:4000'
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ${APPDATA}/gcloud:/root/.config/gcloud:ro
    env_file:
      - .env.local
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/kokorobalance
      - NODE_ENV=development
      - FRONTEND_URL=http://localhost:3002,http://localhost:8081
      - PORT=4000
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    ports:
      - '5434:5432'
    environment:
      - POSTGRES_DB=kokorobalance
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/db/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
