/**
 * Every Material Symbols icon name referenced via <Icon name="..."> across the app,
 * including MDX blog content (content/blog/*.mdx CardGrid `icon:` fields).
 * Used to subset the Google Fonts request so we don't ship the entire icon set (~450KB).
 * When adding a new icon anywhere (component prop or MDX frontmatter/JSX), add its name here too,
 * otherwise it will silently fail to render (the glyph won't be in the downloaded font subset).
 */
export const USED_ICON_NAMES = [
  'air',
  'arrow_back',
  'arrow_downward',
  'back_hand',
  'balance',
  'bar_chart',
  'battery_alert',
  'bolt',
  'chat',
  'check',
  'check_circle',
  'chevron_right',
  'close',
  'delete_forever',
  'description',
  'donut_large',
  'download',
  'edit',
  'edit_note',
  'error',
  'expand_less',
  'expand_more',
  'family_restroom',
  'groups',
  'hearing',
  'heart_broken',
  'home',
  'info',
  'ios_share',
  'lightbulb',
  'local_cafe',
  'lock',
  'mail',
  'menu_book',
  'monitor_heart',
  'open_in_new',
  'palette',
  'person',
  'psychiatry',
  'refresh',
  'restaurant',
  'search',
  'self_improvement',
  'send',
  'settings',
  'shield',
  'smart_toy',
  'spa',
  'star',
  'visibility',
  'warning',
  'water_drop',
  'work',
] as const;
